combine more

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,81 +12,151 @@ env:
   ALL_PYTHON_VERSIONS: "['3.12', '3.13']"
 
 jobs:
-  linux:
-    name: Linux ${{ matrix.platform.name }} ${{ matrix.python-version }}
+
+  build-native:
+    name: ${{ matrix.platform.name }} ${{ matrix.platform.target }} ${{ matrix.python-version }}
     runs-on: ${{ matrix.platform.runner }}
     strategy:
       fail-fast: false
       matrix:
         platform:
-          - name: amd64
+          - name: Linux
             runner: ubuntu-24.04
             target: x86_64
-            native: true
-          - name: aarch64
+          - name: Linux
             runner: ubuntu-24.04-arm
             target: aarch64
-            native: true
-          # - name: armv7
-          #   runner: ubuntu-24.04
-          #   target: armv7
-          #   native: false
+          - name: Windows
+            runner: windows-latest
+            target: x64
+          - name: Windows
+            runner: windows-latest
+            target: x86
+          - name: MacOs
+            runner: macos-13
+            target: x86_64
+          - name: MacOs
+            runner: macos-14
+            target: aarch64
         python-version: ["3.12", "3.13"]
+        include:
+          - name: Windows
+            activate_venv: .venv/Scripts/activate
+          - activate_venv: .venv/bin/activate
+          # Disable docker tests on Windows and MacOS
+          - pytest_args: -m "not docker"
+          - name: Linux
+            manylinux: manylinux_2_34
+            pytest_args: ""
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.python-version }}
+          architecture: ${{ (matrix.platform.name == 'Windows') && matrix.platform.target || '' }}
       - name: Build wheels
         uses: PyO3/maturin-action@v1
         with:
           target: ${{ matrix.platform.target }}
           args: --release --strip --out dist -i python${{ matrix.python-version }}
-          sccache: "false"
-          manylinux: manylinux_2_34
+          sccache: "true"
+          manylinux: ${{ matrix.manylinux }}
       - name: Upload wheels
         uses: actions/upload-artifact@v4
         with:
-          name: wheels-linux-${{ matrix.platform.name }}-${{ matrix.python-version }}
+          name: wheels-${{ matrix.platform.name }}-${{ matrix.platform.target }}-${{ matrix.python-version }}
           path: dist
       - name: 🏗 Install uv
-        if: ${{ matrix.platform.native }}
         uses: astral-sh/setup-uv@v5
         with:
           enable-cache: true
-      - name: pytest (native)
-        if: ${{ matrix.platform.native }}
+      - name: pytest
         shell: bash
         run: |
           rm -rf deebot_client
           uv venv -p ${{ matrix.python-version }}
-          uv export --no-dev --group test --no-emit-project > test-requirements.txt
+          uv export --no-dev --group test --no-emit-project -p ${{ matrix.python-version }} > test-requirements.txt
           uv pip install -r test-requirements.txt
-          source .venv/bin/activate
+          source ${{ matrix.activate_venv }}
           uv pip install --force-reinstall dist/deebot_client-*.whl
-          pytest
-      - name: pytest (different arch)
-        if: ${{ ! matrix.platform.native }}
-        uses: uraimo/run-on-arch-action@v2
-        with:
-          arch: ${{ matrix.platform.target }}
-          distro: ubuntu_latest
-          install: |
-            set -euxo pipefail
-            apt-get update
-            apt-get install -y --no-install-recommends curl python${{ matrix.python-version }}
-            update-ca-certificates
-            curl -LsSf https://astral.sh/uv/install.sh | sh
-            source $HOME/.local/bin/env
-            uv venv -p ${{ matrix.python-version }}
-            uv export --no-dev --group test --no-emit-project -p ${{ matrix.python-version }} > test-requirements.txt
-            uv pip install -r test-requirements.txt
-          run: |
-            set -euxo pipefail
-            source $HOME/.local/bin/env
-            rm -rf deebot_client
-            uv pip install --force-reinstall dist/deebot_client-*.whl
-            pytest
+          # Disable tests, which require docker for now
+          pytest -v ${{ matrix.pytest_args }}
+
+  # linux:
+  #   name: Linux ${{ matrix.platform.name }} ${{ matrix.python-version }}
+  #   runs-on: ${{ matrix.platform.runner }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       platform:
+  #         - name: amd64
+  #           runner: ubuntu-24.04
+  #           target: x86_64
+  #           native: true
+  #         - name: aarch64
+  #           runner: ubuntu-24.04-arm
+  #           target: aarch64
+  #           native: true
+  #         # - name: armv7
+  #         #   runner: ubuntu-24.04
+  #         #   target: armv7
+  #         #   native: false
+  #       python-version: ["3.12", "3.13"]
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-python@v5
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #     - name: Build wheels
+  #       uses: PyO3/maturin-action@v1
+  #       with:
+  #         target: ${{ matrix.platform.target }}
+  #         args: --release --strip --out dist -i python${{ matrix.python-version }}
+  #         sccache: "false"
+  #         manylinux: manylinux_2_34
+  #     - name: Upload wheels
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: wheels-linux-${{ matrix.platform.name }}-${{ matrix.python-version }}
+  #         path: dist
+  #     - name: 🏗 Install uv
+  #       if: ${{ matrix.platform.native }}
+  #       uses: astral-sh/setup-uv@v5
+  #       with:
+  #         enable-cache: true
+  #     - name: pytest (native)
+  #       if: ${{ matrix.platform.native }}
+  #       shell: bash
+  #       run: |
+  #         rm -rf deebot_client
+  #         uv venv -p ${{ matrix.python-version }}
+  #         uv export --no-dev --group test --no-emit-project > test-requirements.txt
+  #         uv pip install -r test-requirements.txt
+  #         source .venv/bin/activate
+  #         uv pip install --force-reinstall dist/deebot_client-*.whl
+  #         pytest
+  #     - name: pytest (different arch)
+  #       if: ${{ ! matrix.platform.native }}
+  #       uses: uraimo/run-on-arch-action@v2
+  #       with:
+  #         arch: ${{ matrix.platform.target }}
+  #         distro: ubuntu_latest
+  #         install: |
+  #           set -euxo pipefail
+  #           apt-get update
+  #           apt-get install -y --no-install-recommends curl python${{ matrix.python-version }}
+  #           update-ca-certificates
+  #           curl -LsSf https://astral.sh/uv/install.sh | sh
+  #           source $HOME/.local/bin/env
+  #           uv venv -p ${{ matrix.python-version }}
+  #           uv export --no-dev --group test --no-emit-project -p ${{ matrix.python-version }} > test-requirements.txt
+  #           uv pip install -r test-requirements.txt
+  #         run: |
+  #           set -euxo pipefail
+  #           source $HOME/.local/bin/env
+  #           rm -rf deebot_client
+  #           uv pip install --force-reinstall dist/deebot_client-*.whl
+  #           pytest
 
   musllinux:
     name: Musllinux ${{ matrix.platform.name }} ${{ matrix.python-version }}
@@ -138,63 +208,7 @@ jobs:
             # Disable tests, which require docker for now
             pytest -v -m "not docker"
 
-  build-others:
-    name: ${{ matrix.platform.name }} ${{ matrix.platform.target }} ${{ matrix.python-version }}
-    runs-on: ${{ matrix.platform.runner }}
-    strategy:
-      fail-fast: false
-      matrix:
-        platform:
-          - name: Windows
-            runner: windows-latest
-            target: x64
-          - name: Windows
-            runner: windows-latest
-            target: x86
-          - name: MacOs
-            runner: macos-13
-            target: x86_64
-          - name: MacOs
-            runner: macos-14
-            target: aarch64
-        python-version: ["3.12", "3.13"]
-        include:
-          - name: Windows
-            activate_venv: .venv/Scripts/activate
-          - name: MacOs
-            activate_venv: .venv/bin/activate
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python-version }}
-          architecture: ${{ (matrix.platform.name == 'Windows') && matrix.platform.target || '' }}
-      - name: Build wheels
-        uses: PyO3/maturin-action@v1
-        with:
-          target: ${{ matrix.platform.target }}
-          args: --release --strip --out dist -i python${{ matrix.python-version }}
-          sccache: "true"
-      - name: Upload wheels
-        uses: actions/upload-artifact@v4
-        with:
-          name: wheels-${{ matrix.platform.name }}-${{ matrix.platform.target }}-${{ matrix.python-version }}
-          path: dist
-      - name: 🏗 Install uv
-        uses: astral-sh/setup-uv@v5
-        with:
-          enable-cache: true
-      - name: pytest
-        shell: bash
-        run: |
-          rm -rf deebot_client
-          uv venv -p ${{ matrix.python-version }}
-          uv export --no-dev --group test --no-emit-project -p ${{ matrix.python-version }} > test-requirements.txt
-          uv pip install -r test-requirements.txt
-          source ${{ matrix.activate_venv }}
-          uv pip install --force-reinstall dist/deebot_client-*.whl
-          # Disable tests, which require docker for now
-          pytest -v -m "not docker"
+
 
   # sdist:
   #   runs-on: ubuntu-latest
